wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707223675.621612
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 70
      - 71
      - 105
      3:
      - 23
      - 35
      4: 3.8.18
      5: 0.16.1
      6: 4.36.2
      8:
      - 5
      13: linux-x86_64
